name: "API Governance"
description: "Run api governance"
author: "johan.enell@qlik.com"

inputs:
  API_SPECIFICATIONS_PATH:
    description: "The path to the api specification file"
    required: true
  API_KEY:
    description: "The api key"
    required: true
  APICULTURIST_S3:
    description: ""
    required: true
  APICULTURIST_GITHUB:
    description: ""
    required: true
  APICULTURIST_TOKEN:
    description: ""
    required: true
  VERSION:
    description: "The released version"

runs:
  using: composite

  steps:
    - name: Prepare API Compliance
      shell: bash
      run: |
        docker pull ghcr.io/qlik-download/api-compliance
        docker create -v /specs --name specs alpine:3.4 /bin/true
        docker cp ${{ inputs.API_SPECIFICATIONS_PATH }} specs:/specs/properties.json

    - name: Run API Compliance
      shell: bash
      run: |
        docker run --volumes-from specs
            -e SPEC_PATHS="${{ inputs.API_KEY }}@/specs/properties.json"
            -e COMMIT_SHA="${{ github.sha }}"
            -e RELEASE_TAG="${{ inputs.VERSION }}"
            -e CREDENTIALS_S3_SECRETKEY="${{ inputs.APICULTURIST_S3 }}"
            -e CREDENTIALS_GITHUB="${{ inputs.APICULTURIST_GITHUB }}"
            -e CREDENTIALS_COLONY="${{ inputs.APICULTURIST_TOKEN }}"
            ghcr.io/qlik-download/api-compliance
