name: "API Governance"
description: "Run api governance"
author: "johan.enell@qlik.com"

inputs:
  API_SPECIFICATION_PATH:
    description: "The path to the api specification file"
    required: true
  API_KEY:
    description: "The api key"
    required: true
  APICULTURIST_S3:
    description: ""
    required: true
  APICULTURIST_GITHUB:
    description: ""
    required: true
  APICULTURIST_TOKEN:
    description: ""
    required: true
  TAG:
    description: "The github tag of the release"
    required: true

runs:
  using: composite

  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.TAG }}
    - name: Run API Compliance
      env:
        API_SPECIFICATION_PATH: ${{ inputs.API_SPECIFICATION_PATH }}
        CURRENT_API_KEY: ${{ inputs.API_KEY }}
        APICULTURIST_S3: ${{ inputs.APICULTURIST_S3 }}
        APICULTURIST_GITHUB: ${{ inputs.APICULTURIST_GITHUB }}
        APICULTURIST_TOKEN: ${{ inputs.APICULTURIST_TOKEN }}
      shell: bash
      run: ${{ github.action_path }}/../release-it/api-compliance.sh ${{ inputs.TAG }}
