name: "Setup environment"
description: "Setup npm environment"
author: "johan.enell@qlik.com"

inputs:
  release:
    description: Controls if semantic-release should do a dry run or not
    required: true
    default: "false"

  debug:
    description: Controls if semantic-release should run in debug mode
    required: false
    default: "false"

runs:
  using: composite

  steps:
    - name: Release
      shell: bash
      id: dry-run
      run: |

    - name: Dry run release
      shell: bash
      run: |
        set -x
        ARGS=
        if [ ${{ inputs.release }} == "false" ]; then
          ARGS="--dry-run"
        fi

        if [ ${{ inputs.debug }} == "true" ]; then
          ARGS="${ARGS} --debug"
        fi

        npx semantic-release $ARGS
