name: "Sematic Release"
description: "Execute semantic-release"
author: "johan.enell@qlik.com"

inputs:
  API_SPECIFICATION_PATH:
    description: "The path to the api specification file"
    required: true
  API_KEY:
    description: "The api key"
    required: true
  APICULTURIST_S3:
    description: ""
    required: true
  APICULTURIST_GITHUB:
    description: ""
    required: true
  APICULTURIST_TOKEN:
    description: ""
    required: true
  GH_TOKEN:
    description: ""
    required: true
  NPM_TOKEN:
    description: ""
    required: true
  release:
    description: ""
    required: true
  release_branches:
    description: ""
    required: false

runs:
  using: composite

  steps:
    - name: Configure semantic release
      shell: bash
      run: cat ${GITHUB_ACTION_PATH}/release.config.cjs > release.config.cjs

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic-release
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        API_SPECIFICATION_PATH: ${{ inputs.API_SPECIFICATION_PATH }}
        API_KEY: ${{ inputs.API_KEY }}
        APICULTURIST_S3: ${{ inputs.APICULTURIST_S3 }}
        APICULTURIST_GITHUB: ${{ inputs.APICULTURIST_GITHUB }}
        APICULTURIST_TOKEN: ${{ inputs.APICULTURIST_TOKEN }}
      with:
        dry_run: ${{ inputs.release == 'false' }}
        branches: ${{ inputs.release_branches }}
        extra_plugins: |
          @semantic-release/exec
          @semantic-release/git
