name: "Release-it"
description: "Execute release-it"
author: "niek.vanstaveren@qlik.com"

inputs:
  GH_TOKEN:
    description: ""
    required: true
  NPM_TOKEN:
    description: ""
    required: true
  package_manager:
    description: ""
    required: true
  monorepo_manager:
    description: ""
    required: false

runs:
  using: composite

  steps:
    - name: Configure release-it
      shell: bash
      run: |
        cat ${GITHUB_ACTION_PATH}/.release-it.js > .release-it.js
    - name: Release it
      shell: bash
      if: ${{ !inputs.monorepo_manager }}
      run: ${{ inputs.package_manager }} release-it --config ${GITHUB_ACTION_PATH}/.release-it.js
    - name: Release it monorepo
      shell: bash
      if: ${{ inputs.monorepo_manager }}
      run: ${{ inputs.package_manager }} run release-it -- --config ${GITHUB_ACTION_PATH}/.release-it.js
