name: "Release-it"
description: "Execute release-it"
author: "niek.vanstaveren@qlik.com"

inputs:
  GH_TOKEN:
    description: ""
    required: true
  NPM_TOKEN:
    description: ""
    required: true
  package_manager:
    description: ""
    required: true
  monorepo_manager:
    description: ""
    required: false

runs:
  using: composite

  steps:
    - name: Configure release-it and git user
      shell: bash
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global url.https://${{ inputs.GH_TOKEN }}@github.com/.insteadOf https://github.com/
        cat ${GITHUB_ACTION_PATH}/.release-it.js > .release-it.js
    - name: Release it
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      shell: bash
      if: ${{ !inputs.monorepo_manager }}
      run: ${{ inputs.package_manager }} release-it --config ${GITHUB_ACTION_PATH}/.release-it.js
    - name: Release it monorepo
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      shell: bash
      if: ${{ inputs.monorepo_manager }}
      run: ${{ inputs.package_manager }} run release-it --config ${GITHUB_ACTION_PATH}/.release-it.js
