name: "Sematic Release"
description: "Execute semantic-release"
author: "johan.enell@qlik.com"

inputs:
  GH_TOKEN:
    description: ""
    required: true
  NPM_TOKEN:
    description: ""
    required: true
  release:
    description: ""
    required: true
  release_branches:
    description: ""
    required: false

runs:
  using: composite

  steps:
    - name: Configure semantic release
      shell: bash
      run: cat ${GITHUB_ACTION_PATH}/release.config.cjs > release.config.cjs

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic-release
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
      with:
        dry_run: ${{ inputs.release == 'false' }}
        branches: ${{ inputs.release_branches }}
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          semantic-release-lerna
