name: "Create and upload dev build"
description: "Create a devbuild for a single package and upload to aws"
author: "niek.vanstaveren@qlik.com"

inputs:
  package:
    description: "Package name"
    required: true
  folder:
    description: "Root folder of the package"
    required: true
  systemjs:
    description: "Systemjs file name"
    required: true
  GH_ACCESS_TOKEN:
    description: "Token for accessing private repos"
    required: false
  NPM_TOKEN:
    description: "Token for accessing npm registry"
    required: false
  NPMRC_ENCODED:
    description: "BASE64 encoded .npmrc file"
    required: false
  ref:
    description: The ref to checkout using actions/checkout
    required: false
    default: ${{ github.ref }}
  QMFE_DEV_ACCESS_KEY_ID:
    description: Access id for aws upload
    required: true
  QMFE_DEV_ACCESS_KEY:
    description: Access key for aws upload

runs:
  using: composite
  steps:
    - name: Setup workspace
      uses: qlik-oss/sn-gh-workflows/actions/setup@v3.0.1
      with:
        GH_ACCESS_TOKEN: ${{ inputs.GH_ACCESS_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        NPMRC_ENCODED: ${{ inputs.QLIK_NPM_DEV_ENCODED }}
    - name: Dev build
      run: pnpm -r --filter ${{ inputs.package }} build:dev
    - name: Upload dev build
      uses: qlik-trial/qmfe-workflows/actions/qmfe-to-aws@v1
      with:
        aws-access-key-id: ${{ inputs.QMFE_DEV_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.QMFE_DEV_ACCESS_KEY }}
        qmfe-id: ${{ inputs.package }}
        source: ${{ inputs.folder }}/dist
        version: ${{ github.event.number }}
        allow-overwrite: true
        include-sourcemaps: true
        aws-bucket-name: "hub-devbuilds"
        s3-key: "nebula"
    - name: Create comment
      id: comment
      uses: qlik-oss/sn-gh-workflows/actions/get-devbuild-comment@dvr/upload-devbuilds
      with:
        package: ${{ inputs.package }}
        namespace: "nebula"
        version: ${{ github.event.number }}
        file: ${{ inputs.systemjs }}
    - name: Find comment
      uses: peter-evans/find-comment@v3
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body-includes: Created a ${{ inputs.package }} dev build
    - name: Comment the PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v4
      with:
        body: ${{ steps.comment.outputs.comment }}
        edit-mode: replace
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        reactions: rocket
