name: "Setup environment"
description: "Setup npm environment"
author: "johan.enell@qlik.com"

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
