name: "Setup environment"
description: "Setup npm environment"
author: "johan.enell@qlik.com"

inputs:
  GH_ACCESS_TOKEN:
    description: "Token for accessing private repos"
    required: false
  NPM_TOKEN:
    description: "Token for accessing npm registry"
    required: false
  NPMRC_ENCODED:
    description: "BASE64 encoded .npmrc file"
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Setup .npmrc
      if: inputs.NPMRC_ENCODED != null
      shell: bash
      env:
        NPMRC_ENCODED: ${{ inputs.NPMRC_ENCODED }}
      run: |
        echo ${{ inputs.NPMRC_ENCODED }} | base64 -d >> ~/.npmrc

    - name: Setup npm access to qlik-trial registry
      if: inputs.GH_ACCESS_TOKEN != null
      shell: bash
      run: |
        npm config set @qlik-trial:registry https://npm.pkg.github.com/
        npm config set "//npm.pkg.github.com/:_authToken=${{ inputs.GH_ACCESS_TOKEN }}"

    - name: Setup npm access to npmjs registry
      if: inputs.NPM_TOKEN != null
      shell: bash
      run: |
        npm config set "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}"

    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
