name: "Setup environment"
description: "Setup npm environment"
author: "johan.enell@qlik.com"

inputs:
  GH_ACCESS_TOKEN:
    description: "Token for accessing private repos"
    required: false
  NPM_TOKEN:
    description: "Token for accessing npm registry"
    required: false
  NPMRC_ENCODED:
    description: "BASE64 encoded .npmrc file"
    required: false
  package_manager:
    description: The desired package manager to be used, [yarn, npm, pnpm, bun]
    required: true
    default: yarn
  ref:
    description: The ref to checkout using actions/checkout
    required: false
    default: ${{ github.ref }}

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: 0

    - name: Setup .npmrc
      if: inputs.NPMRC_ENCODED != null
      shell: bash
      env:
        NPMRC_ENCODED: ${{ inputs.NPMRC_ENCODED }}
      run: |
        echo ${{ inputs.NPMRC_ENCODED }} | base64 -d >> ~/.npmrc

    - name: Setup npm access to qlik-trial registry
      if: inputs.GH_ACCESS_TOKEN != null
      shell: bash
      run: |
        npm config set @qlik-oss:registry https://npm.pkg.github.com/
        npm config set @qlik-trial:registry https://npm.pkg.github.com/
        npm config set "//npm.pkg.github.com/:_authToken=${{ inputs.GH_ACCESS_TOKEN }}"

        echo '[install.scopes]' >> ~/.bunfig.toml
        echo 'qlik-trial = { url = "https://npm.pkg.github.com", token = "${{ inputs.GH_ACCESS_TOKEN }}" }' >> ~/.bunfig.toml
        echo 'qlik-oss = { url = "https://npm.pkg.github.com", token = "${{ inputs.GH_ACCESS_TOKEN }}" }' >> ~/.bunfig.toml

    - name: Setup npm access to npmjs registry
      if: inputs.NPM_TOKEN != null
      shell: bash
      run: |
        npm config set "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}"

    - name: Setup pnpm
      if: inputs.package_manager == 'pnpm'
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Setup bun
      if: inputs.package_manager == 'bun'
      uses: oven-sh/setup-bun@v1

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: ${{ inputs.package_manager != 'bun' && inputs.package_manager || null }}

    - name: Install dependencies
      shell: bash
      run: |
        # Install dependencies
        case ${{ inputs.package_manager }} in
          npm)
            npm ci
            ;;

          yarn)
            yarn install --immutable --frozen-lockfile
            ;;

          pnpm)
            pnpm install --frozen-lockfile
            ;;

          bun)
            bun install --frozen-lockfile
          ;;

          *)
            echo "unknown"
            ;;
        esac
