name: "Setup environment"
description: "Setup npm environment"
author: "johan.enell@qlik.com"

inputs:
  GH_ACCESS_TOKEN:
    description: "Token for accessing private repos"
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn

    - name: Authenticate with private NPM package
      if: inputs.GH_ACCESS_TOKEN != null
      shell: bash
      run: |
        npm set @qlik-trial:registry https://npm.pkg.github.com/
        npm set "//npm.pkg.github.com/:_authToken=${{ inputs.GH_ACCESS_TOKEN }}"

    - name: Authenticate with nebula npm package
      shell: bash
      run: |
        set -eo pipefail
        # Amend auth token for access to public npm registry for @nebula.js packages
        echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" >> ~/.npmrc
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
