name: Build & Release

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean

jobs:
  build_release:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
    - name: Setup workspace
      uses: qlik-oss/sn-gh-workflows/actions/setup@v1

    - name: ESLint
      run: yarn lint

    - name: Typescript
      run: yarn tsc --noEmit

    - name: Restore baseline code coverage
      id: baseline-code-coverage
      uses: actions/cache/restore@v3
      with:
        path: report-baseline.json
        key: baseline-coverage-${{ github.sha }}
        restore-keys: baseline-coverage-

    - name: 'Test'
      if: steps.baseline-code-coverage.outputs.cache-hit == 'true'
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        package-manager: yarn
        test-script: yarn test:unit
        base-coverage-file: report-baseline.json

    - name: Build
      run: yarn build

    - name: Build ext
      run: yarn sense

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dry_run: ${{ !inputs.release }}

    - name: Upload extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-ext
        path: '*-ext/**/*'
        retention-days: 7
