name: Build & Release

on:
  workflow_call:
    inputs:
      release:
        required: true
        type: boolean

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Setup workspace
      uses: qlik-oss/sn-gh-workflows/actions/setup@v1

    - name: ESLint
      run: yarn lint

    - name: Typescript
      run: yarn tsc --noEmit

    - name: Restore baseline code coverage
      id: baseline-code-coverage
      uses: actions/cache@v3
      with:
        path: report-baseline.json
        key: baseline-coverage

    - name: 'Test'
      if: steps.baseline-code-coverage.outputs.cache-hit == 'true'
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        package-manager: yarn
        test-script: yarn test:unit
        base-coverage-file: report-baseline.json

    - name: Build
      run: yarn build

    - name: Release
      uses: qlik-oss/sn-gh-workflows/actions/release@v1
      with:
        release: ${{ inputs.release }}
