name: Test workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        manager: [yarn, pnpm, bun, npm]
    name: ${{ matrix.manager }}
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      package_manager: ${{ matrix.manager }}
      release: false
      api_specification_path: api-spec/spec.json
