name: Build
on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      release: false
      api_specification_path: api-spec/spec.json
