name: Test workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test workflow
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      release: false
      api_specification_path: api-spec/spec.json
