name: Test workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-workflow:
    name: Test workflow
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      release: false
      api_specification_path: api-spec/spec.json

  test-scan-packages:
    name: Test scan packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./actions/scan-packages
        id: scan

      - run: echo '${{ steps.scan.outputs.scripts }}'
      - run: echo '${{ steps.scan.outputs.strategy }}'

      - name: Test if script contains build
        run: |
          if ${{ contains(fromJSON(steps.scan.outputs.scripts), 'build' ) }}; then
            exit 0
          fi
          echo "::error::Couldn't find script build when scanning package.json"
          exit 1

      - name: Test if strategy is correct
        run: |
          if ${{ steps.scan.outputs.strategy == "{ \"fail-fast\": false, \"matrix\": {\"include\": [{ \"package\": \"sn-test\", \"folder\": \"/home/runner/work/sn-gh-workflows/sn-gh-workflows\", \"systemjs\": \"null\" }] }}" }}; then
            exit 0
          fi
          echo "::error::Strategy is not as expected"
          exit 1
